apiVersion: apps/v1
kind: Deployment
metadata:
  name: ens
  namespace: "dev"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ens
  template:
    metadata:
      labels:
        app: ens
    spec:
      containers:
        - name: ens
          image: jumasta/ens:v0.0.1
          ports:
            - containerPort: 8080