---
apiVersion: v1
kind: Service
metadata:
  name: ens
  namespace: dev
  labels:
    app: ens

spec:
  type: ClusterIP
  selector:
    app: ens
  ports:
    - name: http
      port: 8080
      targetPort: 8080